### ISSUE TITLE
Tracking issue: Tact v1.4.0

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact.vim#32]
To be resolved by #33:
- [x] Bitwise NOT `~`
- [x] New augmented assignment operators: `|=`, `&=`, `^=`
- [x] Optional `;` in field declarations of Structs and Messages
- [x] Underscores `_` as unused variable identifiers
- [x] Constant string receivers
- [x] Local type inference for `let` statements
- [x] nativeThrowWhen renamed to nativeThrowIf
