### ISSUE TITLE
Tracking issue: prepare for Tact v1.3.0 upon its release

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact.vim#9]
See: https://github.com/tact-lang/tact/blob/main/CHANGELOG.md
Upstream checklist: https://github.com/tact-lang/tact/issues/280

To do:
- [x] Auto-import all from `@stdlib/ownable` when `@stdlib/stoppable` is imported
- [x] Support escape sequences for strings (highlight them differently)
- [x] Implicit init function
- [x] Support trailing commas in all comma-separated lists
- [x] Add new functions: (`log` and `log2`, `concat` method on StringBuilder, `toString` method/extension function for `Address` type, `isEmpty` and `del` extension functions for maps), 
- [x] The `pow2` power function with base 2
- [x]  The `try` and `try-catch` statements
- [x] Bitwise XOR `^`
- [x] Reserve mode constants (and new lib `@stdlib/reserve`): `ReserveExact`, `ReserveAllExcept`, `ReserveAtMost`, `ReserveAddOriginalBalance`, `ReserveInvertSign`, `ReserveBounceIfActionFail`.
- [x] Add missing `dumpStack()` function
- [x] Struct & Message field punning
- [x] ??? https://github.com/tact-lang/tact/issues/79

**Comment by novusnota** [comment]
Done!
